// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.netty.http.client.tests {
    exports com.timboudreau.netty.http.client.tests;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Inferred from source scan
    requires com.mastfrog.misc;

    // Sibling com.mastfrog/netty-http-test-harness-3.0.0-dev
    requires com.mastfrog.netty.http.test.harness;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.util.function;

    // Inferred from test-source-scan
    requires transitive junit;

}
