// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.netty.http.client {
    exports com.mastfrog.netty.http.client;

    // Sibling com.mastfrog/acteur-headers-3.0.0-dev
    requires com.mastfrog.acteur.headers;

    // Sibling com.mastfrog/acteur-util-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.acteur.util;

    // Sibling com.mastfrog/marshaller-registry-3.0.0-dev
    requires com.mastfrog.marshaller.registry;

    // Inferred from source scan
    requires com.mastfrog.net;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Sibling com.mastfrog/url-3.0.0-dev
    requires com.mastfrog.url;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // derived from io.netty/netty-buffer-0.0.0-? in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires io.netty.buffer;

    // derived from io.netty/netty-codec-http-0.0.0-? in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires io.netty.codec.http;

    // derived from io.netty/netty-handler-0.0.0-? in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires io.netty.handler;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires javassist;

    // Inferred from test-source-scan
    requires junit;

    // derived from com.jcraft/jzlib-1.1.3 in com/jcraft/jzlib/1.1.3/jzlib-1.1.3.pom
    requires jzlib;
    
    requires com.mastfrog.tiny.http.server;
}
