open module com.mastfrog.netty.http.client {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.netty.http.client;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;

    // derived from com.jcraft/jzlib-1.1.3 in com/jcraft/jzlib/1.1.3/jzlib-1.1.3.pom
    requires transitive com.jcraft.jzlib;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.acteur.util;
    requires transitive com.mastfrog.marshaller.registry;
    requires transitive com.mastfrog.tiny.http.server;
    requires transitive com.mastfrog.url;
    requires transitive com.mastfrog.util.net;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;

    // derived from io.netty/netty-codec-http-4.1.76.Final in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http;

    // derived from io.netty/netty-handler-4.1.76.Final in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires transitive io.netty.netty.handler;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.bouncycastle/bcpkix-jdk15on-1.70 in org/bouncycastle/bcpkix-jdk15on/1.70/bcpkix-jdk15on-1.70.pom
    requires transitive org.bouncycastle.pkix;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires transitive org.javassist.javassist;

}
