// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.tiny.http.server {
    exports com.mastfrog.tiny.http.server;

    // derived from io.netty/netty-buffer-0.0.0-? in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires io.netty.buffer;

    // derived from io.netty/netty-codec-http-0.0.0-? in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires io.netty.codec.http;

    // derived from io.netty/netty-handler-0.0.0-? in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires io.netty.handler;

    // derived from io.netty/netty-transport-0.0.0-? in io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.pom
    requires io.netty.transport;
    requires io.netty.common;
    requires io.netty.codec;
    requires java.logging;
}
