open module com.mastfrog.tiny.http.server {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.tiny.http.server;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;

    // derived from io.netty/netty-codec-http-4.1.76.Final in io/netty/netty-codec-http/4.1.76.Final/netty-codec-http-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http;

    // derived from io.netty/netty-handler-4.1.76.Final in io/netty/netty-handler/4.1.76.Final/netty-handler-4.1.76.Final.pom
    requires transitive io.netty.netty.handler;

    // derived from io.netty/netty-transport-4.1.76.Final in io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.pom
    requires transitive io.netty.netty.transport;
    requires java.logging;

}
