open module com.mastfrog.netty.http.test.harness {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.netty.http.test.harness;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.netty.http.client;
    requires transitive com.mastfrog.util.misc;
    requires transitive com.mastfrog.util.net;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
