// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.netty.http.test.harness {
    exports com.mastfrog.netty.http.test.harness;
    
    requires com.fasterxml.jackson.databind;
    requires com.mastfrog.acteur.util;
    requires com.mastfrog.acteur.headers;
    requires com.mastfrog.url;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/util-misc-3.0.0-dev
    requires com.mastfrog.misc;

    // Inferred from source scan
    // Sibling com.mastfrog/util-net-3.0.0-dev
    // Transitive detected by source scan
    requires com.mastfrog.net;

    // Sibling com.mastfrog/netty-http-client-3.0.0-dev
    requires com.mastfrog.netty.http.client;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // Inferred from test-source-scan
    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires junit;

}
